In [155]:
import numpy as np
import pandas as pd


df = pd.read_csv("./data/movielens/ratings.csv")
display(df.head())
df2 = pd.read_csv("./data/movielens/movies.csv")
display(df2.head())

#사용자가 평가한 모든 영화의 전체 평균 평점을 출력하세요
ff=df["rating"].mean()
print("전체 평균 평점 : {}".format(df["rating"].mean()))
##display(ff)

   #userId  movieId  rating  timestamp
0        1        1     4.0  964982703
1        1        3     4.0  964981247
2        1        6     4.0  964982224
3        1       47     5.0  964983815
4        1       50     5.0  964982931

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

전체 평균 평점 : 3.501556983616962

In [12]:
import numpy as np
import pandas as pd

#2. 각 사용자별 평균 평점을 출력하세요 (for문 / boolean indexing)
df = pd.read_csv("./data/movielens/ratings.csv")
display(df.head())
df2 = pd.read_csv("./data/movielens/movies.csv")
display(df2.head())

#빈 데이터프레임 하나 만들기
result_df=pd.DataFrame(columns=['사용자별 평균평점'])
display(result_df)

#사용자 Id부터 뽑아내 보아요
display(df.head())
#unique를 이용해 중복된걸 제거하고 뽑아낼 거에요
user_ids=df["#userId"].unique()
user_ids.shape     ##610명이구나!

#for문돌려
##610개의 user_id를 하나씩 들고올거에요
for user_id in user_ids:
# #각 유저별로 ratings를 추출 --boolean indexing 사용해가지고
    user_mean = df.loc[df["#userId"] == user_id,"rating"].mean()
    result_df.loc[user_id] = user_mean
    
display(result_df.head())

   #userId  movieId  rating  timestamp
0        1        1     4.0  964982703
1        1        3     4.0  964981247
2        1        6     4.0  964982224
3        1       47     5.0  964983815
4        1       50     5.0  964982931

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

Empty DataFrame
Columns: [사용자별 평균평점]
Index: []

   #userId  movieId  rating  timestamp
0        1        1     4.0  964982703
1        1        3     4.0  964981247
2        1        6     4.0  964982224
3        1       47     5.0  964983815
4        1       50     5.0  964982931

   사용자별 평균평점
1   4.366379
2   3.948276
3   2.435897
4   3.555556
5   3.636364

In [96]:
#3. 각 영화별 평균 평점을 다음과 같은 형식으로 출력하세요!

#index(영화ID)  영화제목 영화평점
#0                1@#!     3.41
#1                @!#!@    5.43

import numpy as np
import pandas as pd

result_df = pd.DataFrame(columns=["영화제목", "각 영화별 평균평점"])
display(result_df)
# 사용자 id부터 뽑아내 보아요!
df = pd.read_csv("./data/movielens/ratings.csv")
df2 = pd.read_csv("./data/movielens/movies.csv")
df3=pd.merge(df,df2,on="movieId", how="right")

# display(df.head())
movie_ids = df2["movieId"].unique()
# movie_ids.shape
# display(movie_ids)

# df3=df2["title"]
# df4=df.groupby("movieId").mean()["rating"]
# display(pd.merge(df3,df4,left_index=True, right_index=True))

for movie_id in movie_ids:
    movie_mean=df3.loc[df3["movieId"] == movie_id ,"rating"].mean()
    movie_title=df3.loc[df3["movieId"] == movie_id ,"title"].unique()
    result_df.loc[movie_id] = [movie_title, movie_mean]
#display(result_df)
display(result_df.head())

Empty DataFrame
Columns: [영화제목, 각 영화별 평균평점]
Index: []

                                   영화제목  각 영화별 평균평점
1                    [Toy Story (1995)]    3.920930
2                      [Jumanji (1995)]    3.431818
3             [Grumpier Old Men (1995)]    3.259615
4            [Waiting to Exhale (1995)]    2.357143
5  [Father of the Bride Part II (1995)]    3.071429

In [119]:
#4. 평균 평점이 가장 높은 영화의 제목을 출력하세요
#    (동률이 있는 경우 모두 출력하세요)


import numpy as np
import pandas as pd

result_df = pd.DataFrame(columns=["영화제목", "각 영화별 평균평점"])
result_df1 = pd.DataFrame(columns=["평균평점이 가장 높은 영화제목"])
display(result_df)
display(result_df1)
# 사용자 id부터 뽑아내 보아요!
df = pd.read_csv("./data/movielens/ratings.csv")
df2 = pd.read_csv("./data/movielens/movies.csv")
df3=pd.merge(df,df2,on="movieId", how="right")

# display(df.head())
movie_ids = df2["movieId"].unique()
movie_title=df2["title"].unique()


for movie_id in movie_ids:
    movie_mean = df3.loc[df3["movieId"] == movie_id ,"rating"].mean()
    movie_title = df3.loc[df3["movieId"] == movie_id ,"title"].unique()
    result_df.loc[movie_id] = [movie_title, movie_mean]
display(result_df)

    
display(result_df1)

Empty DataFrame
Columns: [영화제목, 각 영화별 평균평점]
Index: []

Empty DataFrame
Columns: [평균평점이 가장 높은 영화제목]
Index: []

                                                     영화제목  각 영화별 평균평점
1                                      [Toy Story (1995)]    3.920930
2                                        [Jumanji (1995)]    3.431818
3                               [Grumpier Old Men (1995)]    3.259615
4                              [Waiting to Exhale (1995)]    2.357143
5                    [Father of the Bride Part II (1995)]    3.071429
6                                           [Heat (1995)]    3.946078
7                                        [Sabrina (1995)]    3.185185
8                                   [Tom and Huck (1995)]    2.875000
9                                   [Sudden Death (1995)]    3.125000
10                                     [GoldenEye (1995)]    3.496212
11                       [American President, The (1995)]    3.671429
12                   [Dracula: Dead and Loving It (1995)]    2.421053
13                                         [Balto (1995)]    3.125000
14                                         [Nixon (1995)]    3.833333
15                              [Cutthroat Island (1995)]    3.000000
16                                        [Casino (1995)]    3.926829
17                         [Sense and Sensibility (1995)]    3.776119
18                                    [Four Rooms (1995)]    3.700000
19                [Ace Ventura: When Nature Calls (1995)]    2.727273
20                                   [Money Train (1995)]    2.500000
21                                    [Get Shorty (1995)]    3.494382
22                                       [Copycat (1995)]    3.222222
23                                     [Assassins (1995)]    3.125000
24                                        [Powder (1995)]    3.125000
25                             [Leaving Las Vegas (1995)]    3.625000
26                                       [Othello (1995)]    3.500000
27                                  [Now and Then (1995)]    3.333333
28                                    [Persuasion (1995)]    4.227273
29      [City of Lost Children, The (Cité des enfants ...    4.013158
30      [Shanghai Triad (Yao a yao yao dao waipo qiao)...    3.000000
...                                                   ...         ...
188189                       [Sorry to Bother You (2018)]    4.500000
188301                      [Ant-Man and the Wasp (2018)]    3.666667
188675                                    [Dogman (2018)]    3.500000
188751              [Mamma Mia: Here We Go Again! (2018)]    4.500000
188797                                       [Tag (2018)]    4.000000
188833            [The Man Who Killed Don Quixote (2018)]    4.500000
189043                                [Boundaries (2018)]    2.500000
189111                                    [Spiral (2018)]    3.000000
189333             [Mission: Impossible - Fallout (2018)]    3.750000
189381                                  [SuperFly (2018)]    2.500000
189547                              [Iron Soldier (2010)]    1.000000
189713                            [BlacKkKlansman (2018)]    2.500000
190183                         [The Darkest Minds (2018)]    3.500000
190207                                      [Tilt (2011)]    1.500000
190209               [Jeff Ross Roasts the Border (2017)]    4.000000
190213                                 [John From (2015)]    1.000000
190215                              [Liquid Truth (2017)]    1.500000
190219                                     [Bunny (1998)]    1.000000
190221  [Hommage à Zgougou (et salut à Sabine Mamou) (...    1.000000
191005                                   [Gintama (2017)]    4.500000
193565                        [Gintama: The Movie (2010)]    3.500000
193567  [anohana: The Flower We Saw That Day - The Mov...    3.000000
193571                              [Silver Spoon (2014)]    4.000000
193573          [Love Live! The School Idol Movie (2015)]    4.000000
193579         [Jon Stewart Has Left the Building (2015)]    3.500000
193581        [Black Butler: Book of the Atlantic (2017)]    4.000000
193583                     [No Game No Life: Zero (2017)]    3.500000
193585                                     [Flint (2017)]    3.500000
193587              [Bungo Stray Dogs: Dead Apple (2018)]    3.500000
193609              [Andrew Dice Clay: Dice Rules (1991)]    4.000000

[9742 rows x 2 columns]

Empty DataFrame
Columns: [평균평점이 가장 높은 영화제목]
Index: []

In [117]:
#4. 평균 평점이 가장 높은 영화의 제목을 출력하세요
#    (동률이 있는 경우 모두 출력하세요)
res = pd.merge(df2,result_df, left_on="movieId", right_index=True, how="inner")
tt=res.loc[res["각 영화별 평균평점"] == res["각 영화별 평균평점"].max()]

#display(tt)
display(tt[["영화제목"]])

                                                   영화제목
48                                    [Lamerica (1994)]
87               [Heidi Fleiss: Hollywood Madam (1995)]
121                  [Awfully Big Adventure, An (1995)]
405                            [Live Nude Girls (1995)]
432   [In the Realm of the Senses (Ai no corrida) (1...
433                       [What Happened Was... (1994)]
531         [Thin Line Between Love and Hate, A (1996)]
536                            [Denise Calls Up (1995)]
666    [Supercop 2 (Project S) (Chao ji ji hua) (1993)]
865   [Entertaining Angels: The Dorothy Day Story (1...
870                               [Lesson Faust (1994)]
1006                                     [Hype! (1996)]
1037  [Vampire in Venice (Nosferatu a Venezia) (Nosf...
1228                           [Assignment, The (1997)]
1311  [Four Days in September (O Que É Isso, Companh...
1540                                  [Mephisto (1981)]
1647                                 [Knock Off (1998)]
1889  [Ballad of Narayama, The (Narayama bushiko) (1...
2125                              [On the Ropes (1999)]
2234  [Man and a Woman, A (Un homme et une femme) (1...
2237              [Red Sorghum (Hong gao liang) (1987)]
2319                            [Sandpiper, The (1965)]
2329                          [Babes in Toyland (1934)]
2338                            [My Man Godfrey (1957)]
2480  [Black Tar Heroin: The Dark End of the Street ...
2597  [Jonah Who Will Be 25 in the Year 2000 (Jonas ...
2611                          [Madame Sousatzka (1988)]
2639              [All the Vermeers in New York (1990)]
2665                                [Bossa Nova (2000)]
2711               [Vagabond (Sans toit ni loi) (1985)]
...                                                 ...
9423    [Alesha Popovich and Tugarin the Dragon (2004)]
9427                        [Junior and Karlson (1968)]
9443                       [I Am Not Your Negro (2017)]
9495                         [A Plasticine Crow (1981)]
9498                      [There Once Was a Dog (1982)]
9518                [Death Note: Desu nôto (2006–2007)]
9536              [Last Year's Snow Was Falling (1983)]
9537             [Investigation Held by Kolobki (1986)]
9538                           [Karlson Returns (1970)]
9539               [Vacations in Prostokvashino (1980)]
9540                  [Winter in Prostokvashino (1984)]
9542         [Priklyucheniya Kapitana Vrungelya (1979)]
9543                           [Tickling Giants (2017)]
9544      [Vovka in the Kingdom of Far Far Away (1965)]
9546                         [A Detective Story (2003)]
9549                               [Cheburashka (1971)]
9560                      [Wow! A Talking Fish! (1983)]
9561                         [Travels of an Ant (1983)]
9563                                 [Fugitives (1986)]
9568                                   [Empties (2007)]
9575                                 [Obsession (1965)]
9583                        [Gena the Crocodile (1969)]
9585  [On the Trail of the Bremen Town Musicians (19...
9586       [In the blue sea, in the white foam. (1984)]
9588                     [Bobik Visiting Barbos (1977)]
9611                                     [Black Mirror]
9633                            [Loving Vincent (2017)]
9634                            [Blue Planet II (2017)]
9688                          [De platte jungle (1978)]
9711                 [Won't You Be My Neighbor? (2018)]

[296 rows x 1 columns]

In [118]:
#4. 평균 평점이 가장 높은 영화의 제목을 출력하세요
#    (동률이 있는 경우 모두 출력하세요)
res = pd.merge(df2,result_df, left_on="movieId", right_index=True, how="inner")
tt=res.loc[res["각 영화별 평균평점"] == res["각 영화별 평균평점"].max()]

tt.drop("title",axis=1,inplace=True)  
tt.drop("movieId",axis=1,inplace=True)  
tt.drop("각 영화별 평균평점",axis=1,inplace=True)
tt.drop("genres", axis=1, inplace=True)

display(tt.head())

                                                  영화제목
48                                   [Lamerica (1994)]
87              [Heidi Fleiss: Hollywood Madam (1995)]
121                 [Awfully Big Adventure, An (1995)]
405                           [Live Nude Girls (1995)]
432  [In the Realm of the Senses (Ai no corrida) (1...

In [148]:
#5. Comedy 영화 중 가장 평점이 낮은 영화의 제목을 출력하세요
# (동률이 있는경우 모두 출력하세요)

import numpy as np
import pandas as pd

result_df = pd.DataFrame(columns=["영화제목", "각 영화별 평균평점"])
#result_df1 = pd.DataFrame(columns=["평균평점이 가장 높은 영화제목"])
result_df2 = pd.DataFrame(columns=["Comedy영화중 가장 평점이 낮은 영화제목"])

# display(result_df)
# display(result_df1)
# 사용자 id부터 뽑아내 보아요!

df = pd.read_csv("./data/movielens/ratings.csv")
df2 = pd.read_csv("./data/movielens/movies.csv")
df3=pd.merge(df,df2,on="movieId", how="right")

# display(df.head())
movie_ids = df2["movieId"].unique()
movie_title=df2["title"].unique()


for movie_id in movie_ids:
    movie_mean = df3.loc[df3["movieId"] == movie_id ,"rating"].mean()
    movie_title = df3.loc[df3["movieId"] == movie_id ,"title"].unique()
    result_df.loc[movie_id] = [movie_title, movie_mean]
display(result_df.head())

                                   영화제목  각 영화별 평균평점
1                    [Toy Story (1995)]    3.920930
2                      [Jumanji (1995)]    3.431818
3             [Grumpier Old Men (1995)]    3.259615
4            [Waiting to Exhale (1995)]    2.357143
5  [Father of the Bride Part II (1995)]    3.071429

In [153]:
#5. Comedy 영화 중 가장 평점이 낮은 영화의 제목을 출력하세요
# (동률이 있는경우 모두 출력하세요)

res = pd.merge(df2,result_df, left_on="movieId", right_index=True, how="inner")
tt=res.loc[res["각 영화별 평균평점"] == res["각 영화별 평균평점"].min()]
#display(tt)

b_mask = res["genres"].str.contains("Comedy")
#display(b_mask) True/False Mask

comedy_df=res.loc[b_mask,:]
min_ratings=comedy_df["각 영화별 평균평점"].min()
result=comedy_df.loc[comedy_df["각 영화별 평균평점"]==min_ratings]
display(result[["영화제목","각 영화별 평균평점"]])
display(result.shape)
#esult=comedy_df
# result=comedy_df.loc[comedy_df["각 영화별 평균평점"]]
# #display(tt)
# display(result)

                                                   영화제목  각 영화별 평균평점
4439                           [Born to Be Wild (1995)]         0.5
4881                          [Follow Me, Boys! (1966)]         0.5
5258                            [Secret Society (2002)]         0.5
5409  [Boudu Saved From Drowning (Boudu sauvé des ea...         0.5
5453       [Carabineers, The (Carabiniers, Les) (1963)]         0.5
5662               [Jesus Christ Vampire Hunter (2001)]         0.5
5777                         [Are We There Yet? (2005)]         0.5
5795                                [Uncle Nino (2003)]         0.5
6160                    [Leprechaun 4: In Space (1997)]         0.5
6545                            [Daddy Day Camp (2007)]         0.5
6554                     [Brothers Solomon, The (2007)]         0.5
6784                         [Zombie Strippers! (2008)]         0.5
7201                                  [Old Dogs (2009)]         0.5
7553                     [Hard Ticket to Hawaii (1987)]         0.5
7762                          [Arthur Christmas (2011)]         0.5
7820          [Journey 2: The Mysterious Island (2012)]         0.5
8248  [Maria Bamford: The Special Special Special! (...         0.5
8417                        [Haunted House 2, A (2014)]         0.5
8676                             [Tooth Fairy 2 (2012)]         0.5
8893                                     [Aloha (2015)]         0.5
8908             [The Star Wars Holiday Special (1978)]         0.5
8984               [Joe Dirt 2: Beautiful Loser (2015)]         0.5
9056                          [Saving Christmas (2014)]         0.5
9419                               [Bad Santa 2 (2016)]         0.5
9590                           [The Emoji Movie (2017)]         0.5

(25, 5)

In [191]:
#6. 2015 년도에 평가된 모든 Romance영화의 평균 평점은?
#

import datetime
from dateutil.parser import parse
# datetimeobj = datetime.datetime.fromtimestamp(timestamp)
# datetime.datetime.fromtimestamp

stamp=pd.Period(2015, freq='A-DEC')

# display(stamp)
# display(res)
#stamp=res['timestamp'].datetime.datetime.fromtimestamp
ooo=pd.merge(res,df, how="right")
b_mask2=ooo['genres'].str.contains('Romance')

romance_df = ooo.loc[b_mask2,:]
display(b_mask2)
display(romance_df[["각 영화별 평균평점","영화제목","timestamp"]])
display(romance_df)
#b_mask2=res['영화제목'].str.contains('2015').
#print(b_mask2)


#df["이름"] =="강감찬"  ## boolean mask생성 했습니다.
#display(df.loc["행",["이름","학점"]])
#강사님의 큰 그림 : false True false talse 불리안 인덱싱 하나 만들거임!
##display(df.loc[df["이름"] =="강감찬",["이름","학점"]])

0         False
1         False
2         False
3         False
4         False
5         False
6         False
7         False
8         False
9         False
10        False
11        False
12        False
13        False
14        False
15        False
16        False
17        False
18        False
19        False
20        False
21        False
22        False
23        False
24        False
25        False
26        False
27        False
28        False
29        False
          ...
100806    False
100807    False
100808     True
100809    False
100810    False
100811    False
100812    False
100813    False
100814    False
100815    False
100816    False
100817    False
100818    False
100819     True
100820    False
100821    False
100822    False
100823    False
100824    False
100825    False
100826    False
100827    False
100828    False
100829    False
100830    False
100831    False
100832    False
100833    False
100834    False
100835    False
Name: genres, Length: 100836, dtype: bool

        각 영화별 평균평점                                       영화제목   timestamp
325       3.259615                  [Grumpier Old Men (1995)]   964981247
326       3.259615                  [Grumpier Old Men (1995)]   845554296
327       3.259615                  [Grumpier Old Men (1995)]   965707636
328       3.259615                  [Grumpier Old Men (1995)]   856736172
329       3.259615                  [Grumpier Old Men (1995)]   996221045
330       3.259615                  [Grumpier Old Men (1995)]   848994405
331       3.259615                  [Grumpier Old Men (1995)]   869251910
332       3.259615                  [Grumpier Old Men (1995)]  1230932736
333       3.259615                  [Grumpier Old Men (1995)]   847719397
334       3.259615                  [Grumpier Old Men (1995)]  1161519668
335       3.259615                  [Grumpier Old Men (1995)]  1158533415
336       3.259615                  [Grumpier Old Men (1995)]  1112712323
337       3.259615                  [Grumpier Old Men (1995)]  1100183804
338       3.259615                  [Grumpier Old Men (1995)]   840635033
339       3.259615                  [Grumpier Old Men (1995)]  1337200325
340       3.259615                  [Grumpier Old Men (1995)]   844163663
341       3.259615                  [Grumpier Old Men (1995)]   854203124
342       3.259615                  [Grumpier Old Men (1995)]   855947242
343       3.259615                  [Grumpier Old Men (1995)]  1078284750
344       3.259615                  [Grumpier Old Men (1995)]   852114317
345       3.259615                  [Grumpier Old Men (1995)]   955944713
346       3.259615                  [Grumpier Old Men (1995)]  1095662861
347       3.259615                  [Grumpier Old Men (1995)]   849122858
348       3.259615                  [Grumpier Old Men (1995)]   850865480
349       3.259615                  [Grumpier Old Men (1995)]   853918793
350       3.259615                  [Grumpier Old Men (1995)]   975691635
351       3.259615                  [Grumpier Old Men (1995)]  1143424657
352       3.259615                  [Grumpier Old Men (1995)]   966596854
353       3.259615                  [Grumpier Old Men (1995)]   854472084
354       3.259615                  [Grumpier Old Men (1995)]  1186161652
...            ...                                        ...         ...
100185    4.000000                    [A Silent Voice (2016)]  1525286994
100236    3.666667                        [Passengers (2016)]  1510572516
100237    3.666667                        [Passengers (2016)]  1502218032
100238    3.666667                        [Passengers (2016)]  1521490294
100239    3.666667                        [Passengers (2016)]  1526947538
100240    3.666667                        [Passengers (2016)]  1513697360
100241    3.666667                        [Passengers (2016)]  1519593386
100343    4.000000                      [The Big Sick (2017)]  1517440858
100344    4.000000                      [The Big Sick (2017)]  1511535794
100345    4.000000                      [The Big Sick (2017)]  1514776747
100346    4.000000                      [The Big Sick (2017)]  1521397734
100349    3.500000              [Beauty and the Beast (2017)]  1527795993
100350    3.500000              [Beauty and the Beast (2017)]  1535709223
100357    3.750000              [Call Me by Your Name (2017)]  1527108487
100358    3.750000              [Call Me by Your Name (2017)]  1525548280
100359    3.750000              [Call Me by Your Name (2017)]  1518991964
100360    3.750000              [Call Me by Your Name (2017)]  1514777081
100365    1.000000               [Fifty Shades Darker (2017)]  1494880185
100383    3.750000                    [Mulholland Dr. (1999)]  1536152813
100384    3.750000                    [Mulholland Dr. (1999)]  1519121902
100453    3.000000                     [Plain Clothes (1988)]  1519143434
100454    2.500000                     [The Prime Gig (2000)]  1498511865
100602    2.000000                [Boniface's Holiday (1965)]  1520408791
100636    4.500000  [The Night Is Short, Walk on Girl (2017)]  1537109367
100644    3.500000                       [Front Cover (2016)]  1535832645
100662    4.000000                     [Emerald Green (2016)]  1537632338
100712    3.500000                    [Phantom Thread (2017)]  1517370374
100754    3.500000                       [Elsa & Fred (2005)]  1520408986
100808    4.500000      [Mamma Mia: Here We Go Again! (2018)]  1532362151
100819    1.500000                              [Tilt (2011)]  1530148481

[18124 rows x 3 columns]

,movieId,title,genres,영화제목,각 영화별 평균평점,#userId,rating,timestamp
325,3,Grumpier Old Men (1995),Comedy|Romance,[Grumpier Old Men (1995)],3.259615,1,4.0,964981247
326,3,Grumpier Old Men (1995),Comedy|Romance,[Grumpier Old Men (1995)],3.259615,6,5.0,845554296
327,3,Grumpier Old Men (1995),Comedy|Romance,[Grumpier Old Men (1995)],3.259615,19,3.0,965707636
328,3,Grumpier Old Men (1995),Comedy|Romance,[Grumpier Old Men (1995)],3.259615,32,3.0,856736172
329,3,Grumpier Old Men (1995),Comedy|Romance,[Grumpier Old Men (1995)],3.259615,42,4.0,996221045
330,3,Grumpier Old Men (1995),Comedy|Romance,[Grumpier Old Men (1995)],3.259615,43,5.0,848994405
331,3,Grumpier Old Men (1995),Comedy|Romance,[Grumpier Old Men (1995)],3.259615,44,3.0,869251910
332,3,Grumpier Old Men (1995),Comedy|Romance,[Grumpier Old Men (1995)],3.259615,51,4.0,1230932736
333,3,Grumpier Old Men (1995),Comedy|Romance,[Grumpier Old Men (1995)],3.259615,58,3.0,847719397
334,3,Grumpier Old Men (1995),Comedy|Romance,[Grumpier Old Men (1995)],3.259615,64,3.5,1161519668
335,3,Grumpier Old Men (1995),Comedy|Romance,[Grumpier Old Men (1995)],3.259615,68,2.0,1158533415
336,3,Grumpier Old Men (1995),Comedy|Romance,[Grumpier Old Men (1995)],3.259615,91,3.0,1112712323
337,3,Grumpier Old Men (1995),Comedy|Romance,[Grumpier Old Men (1995)],3.259615,100,3.5,1100183804
338,3,Grumpier Old Men (1995),Comedy|Romance,[Grumpier Old Men (1995)],3.259615,102,5.0,840635033
339,3,Grumpier Old Men (1995),Comedy|Romance,[Grumpier Old Men (1995)],3.259615,116,3.5,1337200325
340,3,Grumpier Old Men (1995),Comedy|Romance,[Grumpier Old Men (1995)],3.259615,117,3.0,844163663
341,3,Grumpier Old Men (1995),Comedy|Romance,[Grumpier Old Men (1995)],3.259615,150,3.0,854203124
342,3,Grumpier Old Men (1995),Comedy|Romance,[Grumpier Old Men (1995)],3.259615,151,3.0,855947242
343,3,Grumpier Old Men (1995),Comedy|Romance,[Grumpier Old Men (1995)],3.259615,169,5.0,1078284750
344,3,Grumpier Old Men (1995),Comedy|Romance,[Grumpier Old Men (1995)],3.259615,179,4.0,852114317
345,3,Grumpier Old Men (1995),Comedy|Romance,[Grumpier Old Men (1995)],3.259615,217,1.0,955944713
346,3,Grumpier Old Men (1995),Comedy|Romance,[Grumpier Old Men (1995)],3.259615,226,3.5,1095662861
347,3,Grumpier Old Men (1995),Comedy|Romance,[Grumpier Old Men (1995)],3.259615,240,4.0,849122858
348,3,Grumpier Old Men (1995),Comedy|Romance,[Grumpier Old Men (1995)],3.259615,269,4.0,850865480
349,3,Grumpier Old Men (1995),Comedy|Romance,[Grumpier Old Men (1995)],3.259615,270,3.0,853918793
350,3,Grumpier Old Men (1995),Comedy|Romance,[Grumpier Old Men (1995)],3.259615,288,4.0,975691635
351,3,Grumpier Old Men (1995),Comedy|Romance,[Grumpier Old Men (1995)],3.259615,289,2.5,1143424657
352,3,Grumpier Old Men (1995),Comedy|Romance,[Grumpier Old Men (1995)],3.259615,294,1.0,966596854
353,3,Grumpier Old Men (1995),Comedy|Romance,[Grumpier Old Men (1995)],3.259615,302,3.0,854472084
354,3,Grumpier Old Men (1995),Comedy|Romance,[Grumpier Old Men (1995)],3.259615,307,3.5,1186161652
...,...,...,...,...,...,...,...,...
100185,166291,A Silent Voice (2016),Animation|Drama|Romance,[A Silent Voice (2016)],4.000000,567,3.0,1525286994
100236,166635,Passengers (2016),Adventure|Drama|Romance|Sci-Fi,[Passengers (2016)],3.666667,15,3.5,1510572516
100237,166635,Passengers (2016),Adventure|Drama|Romance|Sci-Fi,[Passengers (2016)],3.666667,18,4.0,1502218032
100238,166635,Passengers (2016),Adventure|Drama|Romance|Sci-Fi,[Passengers (2016)],3.666667,62,3.5,1521490294
100239,166635,Passengers (2016),Adventure|Drama|Romance|Sci-Fi,[Passengers (2016)],3.666667,68,3.0,1526947538
100240,166635,Passengers (2016),Adventure|Drama|Romance|Sci-Fi,[Passengers (2016)],3.666667,125,4.0,1513697360
100241,166635,Passengers (2016),Adventure|Drama|Romance|Sci-Fi,[Passengers (2016)],3.666667,414,4.0,1519593386
100343,168326,The Big Sick (2017),Comedy|Romance,[The Big Sick (2017)],4.000000,111,4.0,1517440858
100344,168326,The Big Sick (2017),Comedy|Romance,[The Big Sick (2017)],4.000000,414,5.0,1511535794
100345,168326,The Big Sick (2017),Comedy|Romance,[The Big Sick (2017)],4.000000,599,3.0,1514776747
100346,168326,The Big Sick (2017),Comedy|Romance,[The Big Sick (2017)],4.000000,601,4.0,1521397734
100349,168366,Beauty and the Beast (2017),Fantasy|Romance,[Beauty and the Beast (2017)],3.500000,212,4.0,1527795993
100350,168366,Beauty and the Beast (2017),Fantasy|Romance,[Beauty and the Beast (2017)],3.500000,596,3.0,1535709223
100357,168492,Call Me by Your Name (2017),Drama|Romance,[Call Me by Your Name (2017)],3.750000,50,3.5,1527108487
100358,168492,Call Me by Your Name (2017),Drama|Romance,[Call Me by Your Name (2017)],3.750000,153,4.5,1525548280
100359,168492,Call Me by Your Name (2017),Drama|Romance,[Call Me by Your Name (2017)],3.750000,318,4.0,1518991964
100360,168492,Call Me by Your Name (2017),Drama|Romance,[Call Me by Your Name (2017)],3.750000,599,3.0,1514777081
100365,168712,Fifty Shades Darker (2017),Drama|Romance,[Fifty Shades Darker (2017)],1.000000,548,1.0,1494880185
100383,170355,Mulholland Dr. (1999),Drama|Mystery|Romance,[Mulholland Dr. (1999)],3.750000,318,3.0,1536152813
100384,170355,Mulholland Dr. (1999),Drama|Mystery|Romance,[Mulholland Dr. (1999)],3.750000,599,4.5,1519121902
100453,172229,Plain Clothes (1988),Comedy|Mystery|Romance|Thriller,[Plain Clothes (1988)],3.000000,599,3.0,1519143434
100454,172233,The Prime Gig (2000),Drama|Romance,[The Prime Gig (2000)],2.500000,599,2.5,1498511865
100602,176621,Boniface's Holiday (1965),Animation|Children|Comedy|Romance,[Boniface's Holiday (1965)],2.000000,89,2.0,1520408791
100636,177939,"The Night Is Short, Walk on Girl (2017)",Animation|Romance,"[The Night Is Short, Walk on Girl (2017)]",4.500000,184,4.5,1537109367
100644,178615,Front Cover (2016),Comedy|Drama|Romance,[Front Cover (2016)],3.500000,596,3.5,1535832645
100662,179511,Emerald Green (2016),Adventure|Drama|Fantasy|Romance,[Emerald Green (2016)],4.000000,210,4.0,1537632338
100712,181315,Phantom Thread (2017),Drama|Romance,[Phantom Thread (2017)],3.500000,599,3.5,1517370374
100754,184349,Elsa & Fred (2005),Comedy|Drama|Romance,[Elsa & Fred (2005)],3.500000,89,3.5,1520408986
100808,188751,Mamma Mia: Here We Go Again! (2018),Comedy|Romance,[Mamma Mia: Here We Go Again! (2018)],4.500000,212,4.5,1532362151
100819,190207,Tilt (2011),Drama|Romance,[Tilt (2011)],1.500000,338,1.5,1530148481

In [193]:
from datetime import datetime
import time

# display(datetimeobj.year)

ooo=pd.merge(res, df, how="right")

romance_df = ooo.loc[ooo["genres"].str.contains("Romance"),:]

start = time.mktime(datetime.strptime('2015-01-01 00:00:00','%Y-%m-%d %H:%M:%S').timetuple())
end = time.mktime(datetime.strptime('2016-01-01 00:00:00','%Y-%m-%d %H:%M:%S').timetuple())

romance_df = ooo.loc[(ooo["timestamp"] >= start) & (ooo["timestamp"] < end),"rating"].mean()

display(romance_df)

3.5140589569160996